### ISSUE TITLE
Url bug in the documentation

### ISSUE THREAD

**Issue by AlexLew95** [skUnity/issues#1]
Same search except that the url changes according to the order of words. If you specify the addon first, it works, otherwise not. It was corrected at one point, but it came back.

![Without the good order](https://image.noelshack.com/fichiers/2018/07/7/1518910549-bug1.png)
![With the good order](https://image.noelshack.com/fichiers/2018/07/7/1518910550-bug2.png)

**Comment by nfell2009** [comment]
I can't replicate this bug.

https://docs.skunity.com/syntax/search/write%20addon:skutilities and https://docs.skunity.com/syntax/search/addon:skutilities%20write work as intended. In your photos the URL does have the search bit removed, but you haven't provided enough information as to what you clicked to cause that.

**Comment by Nicofisi** [comment]
Same for me @nfell2009, both work as intended on mobile Chrome.

@AlexLew95 what browser are you on? Firefox?

**Comment by Nicofisi** [comment]
I downloaded it and can't reproduce either 🤷‍♂️ 

https://nicofi.si/ss/wEHHMOClAx.png

**Comment by AlexLew95** [comment]
@Nicofisi To reproduce this bug, you have to click on the search bar, write "write" then go down in the addons and click on "SkUtilities" and finally click on ENTER. Normally the url will be different.

**Comment by Nicofisi** [comment]
Oh, then yeah, the `syntax` part is indeed missing then, even on Chrome.

Btw, this shouldn't appear twice should it? https://nicofi.si/ss/VbWhy5UE5V.gif

**Comment by AlexLew95** [comment]
Yeah, it's too a problem

**Comment by nfell2009** [comment]
Fixed the issue. Should now be resolved and working as normal
