### ISSUE TITLE
Some Docs Elements do not parse html translations correctly

### ISSUE THREAD

**Issue by JRoy** [skUnity/issues#3]
I have found some use cases where HTML translation codes are not being parsed as such here:

In the resource staff queue:
![In the docs](https://i.gyazo.com/287bcfadca856dceff835bf3fdc8733f.png)

Syntax Element (ID: 22)
![A docs element](https://i.gyazo.com/2654a6bb70181b7292c6ae2a532a9217.png)

**Comment by nfell2009** [comment]
Will sort this at some point.

**Comment by nfell2009** [comment]
Should be fixed with the new docs data
